apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: shop-backend
          image: ghcr.io/jangruebener/k8s-shop-backend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
spec:
  type: ClusterIP
  selector:
    app: shop-backend
  ports:
    - port: 80
      targetPort: 3000